### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by maluramichael** [Devnetik/react-native-slide-view#2]
Like onOpened and onClosed

**Comment by Aidurber** [comment]
Hi @maluramichael ,
I've taken a stab at this see #11 
I assumed the onOpened and onClosed were to be called after animations were complete?

Also, I've just realised I should update the README with the new props, will do that one now.

**Comment by Aidurber** [comment]
README updated

**Comment by maluramichael** [comment]
Merged
